skeleton/src/Entity/Parts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartsRepository")
 */
class Parts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $styles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pictures;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Groupe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?users
    {
        return $this->author;
    }

    public function setAuthor(?users $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getStyles(): ?string
    {
        return $this->styles;
    }

    public function setStyles(?string $styles): self
    {
        $this->styles = $styles;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPictures(): ?string
    {
        return $this->pictures;
    }

    public function setPictures(?string $pictures): self
    {
        $this->pictures = $pictures;

        return $this;
    }

    public function getGroupe(): ?string
    {
        return $this->Groupe;
    }

    public function setGroupe(?string $Groupe): self
    {
        $this->Groupe = $Groupe;

        return $this;
    }
}

skeleton/src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class, [
                'label'=> "Pseudo :",
                'attr'=>[
                    'placeholder' => "nom d'utilisateur...",
                ]
            ])

            ->add('password' , PasswordType::class, [
                'label'=>'Mot de passe :',
                'attr'=>[
                    'placeholder'=>'mot de passe...'
    ]
            ])
            ->add('confirm_password', PasswordType::class, [
                'label'=> 'Confirmez votre mot de passe :',
                'attr'=>[
                    'placeholder'=>'confirmez votre mot de passe..'
    ]
            ])

            ->add('mail', EmailType::class, [
                'label'=> 'Email :',
                'attr'=>[
                    'placeholder'=> 'adresse email...'
                ]
            ])

            ->add('city', TextType::class, [
                'label'=>'Ville :',
                'required' => false,
                'attr'=> [
                    'placeholder'=> 'votre ville...'
                ]
            ])

            ->add('age', IntegerType::class, [
                'label'=> 'Age :',
                'required' => false,
                'attr'=> [
                    'placeholder'=> 'votre age ...'
                ]
            ])

            ->add('influences', TextareaType::class, [
                'label'=> 'Influences :',
                'required' => false,
                'attr'=> [
                    'placeholder'=>'Vos artistes ou groupes ...'
                ]
            ])

            ->add('styles', TextareaType::class, [
                'label'=> 'Style(s) :',
                'required' => false,
                'attr'=> [
                    'placeholder'=>'Votre/vos style(s) de musique ...'
                ]
            ])

            ->add('avatar', FileType::class, [
                'label'=>'Avatar/Photo de profil :',
                'required'=> false,
                'attr'=>[
                    'accept'=>"image/png, image/jpeg, image/jpg",
                ]
            ])

            ->add('Enregistrer', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-secondary',
                ]
            ])
        ;

        $builder
            ->get('avatar');

    }



    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
            'method' => 'post',
        ]);
    }
}

skeleton/src/Controller/UsersController.php
<?php

namespace App\Controller;


use App\Entity\SearchUserInfluences;
use App\Entity\SearchUserStyles;
use App\Entity\SearchUsername;
use App\Entity\Users;
use App\Form\SearchInfluencesType;
use App\Form\SearchStylesType;
use App\Form\SearchUsernameType;
use App\Form\UsersType;
use App\Repository\PartsRepository;
use App\Repository\UsersRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class UsersController extends AbstractController
{
    /*create folder for register the avatar profile of user*/
    const AVATAR_DIRECTORY = "img/avatar_directory";

    /**
     * @Route("/users", name="users_index")
     */
    public function index(Request $request, UsersRepository $usersRepository, PaginatorInterface $paginator): Response
    {

            $users = $paginator->paginate($usersRepository->findAll(),
            $request->query->getInt('page',1),6);
            $role = $this->getUser()->getRoles();

        return $this->render('users/index.html.twig', [
            'controller_name' => 'UsersController',
            'users' => $users,
            'role' => $role[0],
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/registration" , name="registration_user")
     */
    public function registration(Request $request, UserPasswordEncoderInterface $encoder) : Response
    {
        /*Register a new user with form*/
        $user = new Users();;
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $avatar_img = $form->get('avatar')->getData();

            /*if the user doesn't record a profile picture , default value : "profil_default.png"*/
            if ($_FILES['users']['name']['avatar'] == "") {
                $user->setAvatar('profil_default.png');
            } else {
                $avatar_name = $this->generateUniqueFileName();
                $avatar_img->move(self::AVATAR_DIRECTORY, $avatar_name . ".png");
                $user->setAvatar($avatar_name . ".png");
            }
            $PasswordEncode = $encoder->encodePassword($user, $user->getPassword());
            $user->setRoles('ROLE_USER');
            $user->setPassword($PasswordEncode);
            $EmptyManager = $this->getDoctrine()->getManager();
            $EmptyManager->persist($user);
            $EmptyManager->flush();

            return $this->render('users/login.html.twig',
                ['form' => $form->createView(),
                    'user' => $this->getUser(),
                ]);
        }

        return $this->render('/users/registration.html.twig',
            ['form' => $form->createView(),
                'user' => $this->getUser(),
            ]);
    }
    /**
     * @Route("/connexion" , name="security_connexion")
     */
    public function connexion(AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();

        return $this->render('users/login.html.twig',
            ['error' => $error,
             'user' => $this->getUser(),
            ]);
    }

    /**
     * @Route("/logout" , name="logout_user")
     */
    public function logout()
    {

    }
    /**
     * @Route("/", name="check")
     */
    public function check()
    {
        /*check 'role' of the user connects.*/
        if (true == $this->get('security.authorization_checker')->isGranted('ROLE_USER')) {
            return $this->redirectToRoute('parts_index');
        }
        if (true == $this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('parts_index');
        } else {
            return $this->redirectToRoute('registration_user');

        }
    }
    /**
     * @return Response
     * @Route("/profile/{id}/show_profile" , name="user_profile" , methods={"GET"})
     */
    public function profile_user($id,Request $request, PartsRepository $partsRepository, UsersRepository $usersRepository , PaginatorInterface $paginator): Response
    {
        /*Create view of user profile with his description and list of his score drums set*/
        $user = $usersRepository->find($id);
        $parts = $paginator->paginate($partsRepository->findBy(['author'=> $user]),
        $request->query->getInt('page',1), 2);
        $role = $this->getUser()->getRoles();

        return $this->render('users/show_profile.html.twig',
            ['users' => $user,
                'user' => $this->getUser(),
                'id_user' => $id,
                'role' => $role[0],
                'parts' => $parts,
                ]);
    }
    /**
     * @Route("/profile/{id}/edit_profile", name="edit_urprofile" , methods={"GET" , "POST"})
     *
     */
    public function edit_profile(Request $request, Users $user, UserPasswordEncoderInterface $encoder): Response
    {
        /*Edit user profile by form*/
        $avatarUser = $user->getAvatar();
        $user->setAvatar('');
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $avatar_img = $form->get('avatar')->getData();

            if ($_FILES['users']['name']['avatar'] == "") {
                $user->setAvatar($avatarUser);
            } else {
                $avatar_name = $this->generateUniqueFileName();
                $avatar_img->move(self::AVATAR_DIRECTORY, $avatar_name . ".png");
                $user->setAvatar($avatar_name . ".png");
            }
            $PasswordEncode = $encoder->encodePassword($user, $user->getPassword());
            $user->setRoles('ROLE_USER');
            $user->setPassword($PasswordEncode);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('parts_index', [
                'id' => $this->getUser()->getId(),
            ]);

        }
        return $this->render('users/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/profile/search", name="users_search")
     *
     */
    public function search(Request $request, UsersRepository $usersRepository , PaginatorInterface $paginator): Response
    {
        $users = $paginator->paginate($usersRepository->findAll(), $request->query->getInt('page', 1), 5);

        $search_u = new SearchUsername();
        $SearchFormBy_username = $this->createForm(SearchUsernameType::class, $search_u);
        $SearchFormBy_username->handleRequest($request);
        $data = $SearchFormBy_username->getData();

        if ($SearchFormBy_username->isSubmitted()) {
            if ($data->getUsername()) {
                $search_u->setSearchUsername($data->getUsername());
                $users = $paginator->paginate($usersRepository->FindUserByName($search_u)->getResult(),
                    $request->query->getInt('page' , 1), 5
                );

            }
        }

        $search_s = new SearchUserStyles();
        $SearchFormBy_style = $this->createForm(SearchStylesType::class, $search_s);
        $SearchFormBy_style->handleRequest($request);
        $data2 = $SearchFormBy_style->getData();


        if ($SearchFormBy_style->isSubmitted()) {
            if ($data2->getStyles()) {
                $search_s->setSearchStyle($data2->getStyles());
                $users = $paginator->paginate($usersRepository->FindUserByStyles($search_s)->getResult(),
                    $request->query->getInt('page', 1), 5);

            }
        }

        $search_i = new SearchUserInfluences();
        $SearchFormBy_influences = $this->createForm(SearchInfluencesType::class, $search_i);
        $SearchFormBy_influences->handleRequest($request);
        $data3 = $SearchFormBy_influences->getData();


        if ($SearchFormBy_influences->isSubmitted()) {
            if ($data3->getInfluences()) {
                $search_i->setSearchInfluence($data3->getInfluences());
                $users = $paginator->paginate($usersRepository->FindUserByInfluences($search_i)->getResult(),
                    $request->query->getInt('page', 1),6);

            }
        }

        return $this->render('users/search.html.twig', [
            'controller_name' => 'UsersController',
            'users' => $users,
            'user' => $this->getUser(),
            'form_U' => $SearchFormBy_username->createView(),
            'form_S' => $SearchFormBy_style->createView(),
            'form_I' => $SearchFormBy_influences->createView(),
        ]);
    }

    /*this function create a single name for each file*/
    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }
}

skeleton/templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}
    <div class="row">
        <div class="formView col-sm-9">

        {% if app.user.id == user.id or app.user == 'admin' %}
        {{ form_start(form) }}
            {{ form_row(form.username) }}
            {{ form_row(form.password) }}
            {{ form_row(form.confirm_password) }}
            {{ form_row(form.mail) }}
            {{ form_row(form.city) }}
            {{ form_row(form.age) }}
            {{ form_row(form.influences) }}
            {{ form_row(form.styles) }}
            {{ form_row(form.avatar) }}
        {{ form_end(form) }}
        {% else %}
         <p>Vous n'êtes pas autorisé à accéder à cette page</p>
        {% endif %}
    </div>
</div>
{% endblock %}

skeleton/templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Admin !{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-12 table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Avatar/Photo.profil</th>
                    <th scope="col">Nom/pseudo</th>
                    <th scope="col">Ville</th>
                    <th scope="col">Age</th>
                    <th scope="col">Styles</th>
                    <th scope="col">influences(artistes,groupes)</th>
                </tr>
            </thead>
        <tbody>

        {% for user in users %}
            <tr class="table-light">
                <td><img class="img_avatar" src="../img/avatar_directory/{{ user.avatar }}" alt="image de profil de l'utilisateur"></td>
                <td><a href="{{ path('edit_urprofile', {'id' : user.id})  }}">{{ user.username }}</a></td>
                <td>{{ user.city }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.styles }}</td>
                <td>{{ user.influences }}</td>
                {% endfor %}
            </tr>
        </tbody>

    </table>
    </div>
</div>

    <div class="pagination-sm d-flex justify-content-center">
        {{ knp_pagination_render(users) }}
    </div>
{% endblock %}

skeleton/templates/users/login.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <form action="{{ path('security_connexion') }}" method="post" name="">
        <div class="formLogin row">
        {% if error %}
            <div><p>Pseudo et/ou mot de passe incorrect !</p></div>
        {% endif %}
                <div class="col-sm-12">
                    <label for="username">Pseudo :</label>
                    <input class="form-control" type="text" placeholder="pseudo" required name="_username" id="username">

                    <label for="password">Mot de passe :</label>
                    <input class="form-control" type="password" placeholder="mot de passe" required name="_password" id="password">
                    <button type="submit" class="btn btn-primary">Envoyez</button>
                </div>
            </div>
    </form>
{% endblock %}

skeleton/templates/users/registration.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="row">
    <div class="formView col-sm-6">
        <p>Les champs avec * sont obligatoires</p>
        {{ form_start(form) }}
        {{ form_row(form.username) }}
        {{ form_row(form.password) }}
        {{ form_row(form.confirm_password) }}
        {{ form_row(form.mail) }}
        {{ form_row(form.city) }}
        {{ form_row(form.age) }}
        {{ form_row(form.influences) }}
        {{ form_row(form.styles) }}
        {{ form_row(form.avatar) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

skeleton/templates/users/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rechercher un utilisateur{% endblock %}

{% block body %}
<div class="row">
    <div class="formView col-sm-6">
        <p class="text-info text-center">/!\ Limite de la recherche à 1 catégorie par recherche</p>
        <p class="text-center">Chercher par :</p>
        {{ form_start(form_U) }}
        {{ form_row(form_U.username) }}
        <p class="text-center">ou</p>
        {{ form_row(form_S.styles) }}
        <p class="text-center">ou</p>
        {{  form_row(form_I.influences) }}
        <button class="btn btn-secondary">Rechercher</button>
        {{ form_end(form_U) }}
    </div>
</div>

<div class="row">
    <div class="col-sm-12 table-responsive">
        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Avatar/Photo.profil</th>
                <th scope="col">Nom/pseudo</th>
                <th scope="col">Ville</th>
                <th scope="col">Age</th>
                <th scope="col">Styles</th>
                <th scope="col">influences(artistes,groupes)</th>
            </tr>
    </thead>

    <tbody>
         {% for user in users %}
            <tr class="table-primary">
                <td><img class="img_avatar" src="../img/avatar_directory/{{ user.avatar }}" alt="image de profil de l'utilisateur"></td>
                <td><a href="{{ path('user_profile', {'id' : user.id})  }}">{{ user.username }}</a></td>
                <td>{{ user.city }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.styles }}</td>
                <td>{{ user.influences }}</td>
         {% endfor %}
            </tr>
    </tbody>
        </table>
    </div>
</div>
<div class="pagination-sm d-flex justify-content-center">
    {{ knp_pagination_render(users) }}
</div>

{% endblock %}

skeleton/templates/users/show_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<div class="row">
   <div class="card text-white bg-secondary mb-3 profileUserCard col-sm-9">
       <ul style="list-style-type: none; padding-right: 13%;">
            <li><img class="img_avatar" src="../../img/avatar_directory/{{ users.avatar }}" alt="Picture profile of this user"></li>
            <li class="card-text">
                <span class="CategoryNamePartsBold">Pseudo : </span>
                    <p>{{ users.username }}</p>
            </li>
            <li class="card-text">
                <span class="CategoryNamePartsBold">Ville : </span>
                    <p>{{ users.city }}</p>
            </li>
            <li class="card-text">
                <span class="CategoryNamePartsBold">Age :</span>
                    <p>{{ users.age }}</p>
            </li>
            <li class="card-text">
                <span class="CategoryNamePartsBold">Style(s) de musique : </span>
                    <p>{{ users.styles }}</p>
            </li>
            <li class="card-text">
                <span class="CategoryNamePartsBold">Artistes ou groupes : </span>
                    <p>{{ users.influences }}</p>
            </li>
       </ul>
   </div>
</div>

<div class="row">
    <div class="col-sm-12 table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Style(s)</th>
                    <th>Type</th>
                    <th>Image</th>
                    {% if app.user.id ==  id_user  %}
                        <th>Edition</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                    <h4>Liste de ses morceaux </h4>
                        {% for part in parts %}
                            <tr>
                                <td class="align-middle">{{ part.title }}</td>
                                <td class="align-middle">{{ part.styles }}</td>
                                <td class="align-middle">{{ part.type }}</td>
                                <td class="align-middle">
                                    <a href="../../img/sheetmusic_directory/{{ part.pictures }}" data-lightbox="img_profile" data-title="img_UserProfile">Voir</a>
                                </td>

                                    {% if app.user.id ==  id_user or role == 'ROLE_ADMIN'  %}
                                <td class="align-middle">
                                    <a class="btn btn-primary" href="{{ path('parts_edit', {'id': part.id}) }}">Editer</a>
                                </td>
                                <td class="align-middle">
                                    <div style="margin-top: 0">{{ include('parts/_delete_form.html.twig') }}</div>
                                </td>
                                {% endif %}
                                <td class="align-middle">
                                    <a class="btn btn-primary" href="/img/sheetmusic_directory/{{ part.pictures }}" download="{{ part.title }}-{{ part.groupe }}_by{{ part.author }}">Télécharger</a>
                                </td>

                            </tr>
                        {% endfor %}
            </tbody>
        </table>
    </div>
</div>
    <div class="pagination-sm d-flex justify-content-center">
        {{ knp_pagination_render(parts) }}
    </div>








{% endblock %}